### PR TITLE
Handle other type of truststore

### PR DESCRIPTION
**Pull request by zigarn**
Only the discouraged JKS was available

### CODE REVIEW

**Comment by zigarn** [comment]
Sadly, use of secrets is breaking the CI when source branch is from a fork:
 - from #340: `secrets.FOSSA_API_KEY` breaking fossa-scan
 - from #341: `secrets.SCHEMA_REGISTRY_URL` breaking e2e tests
 - from #348: `secrets.SEMGREP_PUBLISH_TOKEN` breaking semgrep

**Comment by zigarn** [comment]
The GitHub workflow should be changed to be triggered on `pull_request_target` (cf. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target): https://github.com/splunk/kafka-connect-splunk/blob/4bc558607b3bea776b57b858d6f437c62d0ef154/.github/workflows/ci_build_test.yaml#L4

**Comment by foram-splunk** [comment]
Hi @zigarn, I've updated the workflow.

Can you please rebase this PR?

**Comment by zigarn** [comment]
@foram-splunk: thanks for updating the workflow. PR rebased and workflow waiting for approval.

**Review by foram-splunk — APPROVED** [review]

**Pull request merged**
