### PR TITLE
Fix: record tracker does not support concurrent event batch removal

### PR DESCRIPTION
**Pull request by ludovic-boutros**
This PR aims to fix the issue #423. 

The record tracker uses `ConcurrentNavigableMap` iterators.
These iterators are Weakly-Consistent iterators.
That means that a thread will not see reflected changes made by another concurrent thread.
Therefore, events can be removed multiple times and the total number of event is not accurate and can become a negative number.

The idea of this fix is to first make sure that the total number of event never become a negative number anymore and given the strategy, we don't need to clean the event batches in parallel. Only one thread needs do the job at some point. 

Another approach would be to use the batch input parameter of the function `removeAckedEventBatches`, but I did not want to change the design too much.

### CODE REVIEW

**Comment by ludovic-boutros** [comment]
I have rewritten the code using a far simpler approach.

**Comment by wojtekzyla** [comment]
Hi @ludovic-boutros. I took over this project after @VihasMakwana. I'll look into this PR

**Review by wojtekzyla — APPROVED** [review]

**Comment by ludovic-boutros** [comment]
Hello @wojtekzyla, any news on this issue? This is a critical issue for my customer.

**Comment by ludovic-boutros** [comment]
Thank you, @wojtekzyla! Would it be possible to make a release, please?

**Pull request merged**
